export const SELECT_USER_BY_EMAIL = "SELECT * FROM USERS WHERE USEREMAIL=$1";
export const SELECT_USER_ID_BY_EMAIL = "SELECT USERID FROM USERS WHERE USEREMAIL=$1";
export const SELECT_USER_ID_BY_EMAIL_AND_PASSWORD = "SELECT USERID FROM USERS WHERE USEREMAIL=$1 AND PASSWORD=$2";
export const INSERT_USER = "INSERT INTO USERS(userEmail, PASSWORD, FIRSTNAME, LASTNAME, CREATEDON) VALUES($1, $2, $3, $4, $5)";